// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQq0-Wpo8Fq5HBNBAqcjMm9d8BWIkhoAE',
    appId: '1:707064458562:web:02a802002fd9e7896decdb',
    messagingSenderId: '707064458562',
    projectId: 'pawfect-care-849d1',
    authDomain: 'pawfect-care-849d1.firebaseapp.com',
    storageBucket: 'pawfect-care-849d1.firebasestorage.app',
    measurementId: 'G-SWVN4PWKGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0e2vAko3tmzAs8x8oxcu3oS9m7rpVmDU',
    appId: '1:707064458562:android:08d3736af58413ab6decdb',
    messagingSenderId: '707064458562',
    projectId: 'pawfect-care-849d1',
    storageBucket: 'pawfect-care-849d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkovMMMDmalnG5-UVN8aj3RhJgnKmu_Kk',
    appId: '1:707064458562:ios:374f52b8f6d077796decdb',
    messagingSenderId: '707064458562',
    projectId: 'pawfect-care-849d1',
    storageBucket: 'pawfect-care-849d1.firebasestorage.app',
    iosBundleId: 'com.example.pawfectCare',
  );
}
